export const projects = [
  {
    title: 'UNISWAP CLONE',
    description:"This is a Web 3.0 Uniswap Clone Application built with Next JS, styled with Tailwind CSS, using Solidity for the smart contract, and well tested using hardhat. I added user authentication using MetaMask and also Stored data and information about each transaction in Sanity.io. I used GROQ to retrieve data from Sanity Studio and displayed it on the frontend. Created, sent and received functionality for tokens on the blockchain with Solidity. This app is deployed and hosted on Vercel.",
    image: '/images/1.png',
    tags: ['Next JS', 'Taliwind CSS', 'Solidity', 'Hardhat', 'Sanity'],
    source: 'https://github.com/d0lbangi/Web3-uniswap-clone-.git',
    visit: 'https://uniswap-clone-lemon.vercel.app/',
    id: 0,
  },
  {
    title: 'Full Web3 Mint Website',
    description: "The App that allows users to mint NFT, and is called A Flashy Full WEb3 Mint Website and built with using React, Ethers, Hardhat, and Chakra - from start to finish. Writing a Smart Contract for NFT Mint and deploy it to Test Network. Creating a Full Mint Website with some Life with CSS Styling",
      image: '/images/2.png',
      tags: ['React', 'Ethers', 'Solidity', 'Hardhat', 'Chakra'],
    source: 'https://github.com/d0lbangi/RoboPunksNFT.git',
    visit: 'https://full-web3-mint-website.vercel.app/',
    id: 1,
  },
  {
    title: 'Buy Me A Coffee',
    description:"Built a frontend website for a decentralized application with using the Hardhat development environment to build, test, and deploy it with Ethers.js to interact with your deployed smart contract. MetaMask wallet to the Ethereum, Goerli test network that allows visitors to send you (fake) ETH as tips and leave nice messages, using connecting, and an Alchemy RPC endpoint.",
    image: '/images/coffee.png',
    tags: ['Next JS', 'Taliwind CSS', 'MetaMask', 'Hardhat'],
    source: 'https://github.com/d0lbangi?tab=repositories',
    visit: 'https://buy-me-a-coffee-omega.vercel.app/',
    id: 2,
  },
  {
    title: 'KakaoTalk CLONE',
    description:"This is a Web Kakao Clone Application built with HTML5, Advanced CSS3, styled with Tailwind CSS. Created function including Status Bar, Chat, Friends, Find, Settings, Message Animations, Chats, and More.",
    image: '/images/kakao.png',
    tags: ['HTML5', 'Advanced CSS3'],
    source: 'https://github.com/d0lbangi/kokoa-clone',
    visit: 'https://kokoa-clone.vercel.app/',
    id: 3,
  },
  {
    title: 'Portfolio Website',
    description:"This is a Portfolio Website built with Next JS, React, and styled with Tailwind CSS. This app is deployed and hosted on Vercel. Will continously be updated as long as projects are finished.",
    image: '/images/portfolio.png',
    tags: ['Next JS', 'Taliwind CSS', 'React'],
    source: 'https://github.com/d0lbangi/Portfolio-Website',
    visit: 'https://portfolio-website-eight-blush.vercel.app/',
    id: 4,
  },
  {
    title: 'solidity-todo-list',
    description:"This is a Todo list Website Application built with Next.js & Truffle + Tailwind CSS using Solidity for the smart contract, and well tested using hardhat. I added user authentication using MetaMask and also Stored data and information about each transaction. Created, sent and received functionality for tokens on the blockchain with Solidity. This app is deployed and hosted on Vercel.",
    image: '/images/todo.png',
    tags: ['Next JS', 'Taliwind CSS', 'Solidity', 'Hardhat', 'Truffle'],
    source: 'https://github.com/d0lbangi?tab=repositories',
    visit: 'https://solidity-todo-list.vercel.app/',
    id: 5,
  }];

export const TimeLineData = [
  { year: 2020, text: 'Started my journey as a RF Test Development Engineering @JCET', },
  { year: 2021, text: 'Started Blockchain project', },
  { year: 2022, text: 'Working as a Blockchain developer @asimula', },
];